// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiN8gawT58RQgtUzt7WJmg5Te0jUQNLLQ',
    appId: '1:380105473471:web:cdc8c0ac4502cfe2f4750a',
    messagingSenderId: '380105473471',
    projectId: 'zainservices-e4add',
    authDomain: 'zainservices-e4add.firebaseapp.com',
    storageBucket: 'zainservices-e4add.appspot.com',
    measurementId: 'G-FZCY442KPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm_g0BRFxLzOqlJMBV-ZulXWkmTlol0pQ',
    appId: '1:380105473471:android:2f2bbfe59662f197f4750a',
    messagingSenderId: '380105473471',
    projectId: 'zainservices-e4add',
    storageBucket: 'zainservices-e4add.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKK5csvr3Of0FP_WKGMhRuxVGlNzkPVRY',
    appId: '1:380105473471:ios:7753b15f93b44a3ff4750a',
    messagingSenderId: '380105473471',
    projectId: 'zainservices-e4add',
    storageBucket: 'zainservices-e4add.appspot.com',
    iosBundleId: 'com.example.zainServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKK5csvr3Of0FP_WKGMhRuxVGlNzkPVRY',
    appId: '1:380105473471:ios:a1b96888f8f7f12ef4750a',
    messagingSenderId: '380105473471',
    projectId: 'zainservices-e4add',
    storageBucket: 'zainservices-e4add.appspot.com',
    iosBundleId: 'com.example.zainServices.RunnerTests',
  );
}
